"use node";

import { action } from "../_generated/server";
import { internal } from "../_generated/api";
import { api } from "../_generated/api";
import {
  callClaude,
  BRIEFING_SYSTEM_PROMPT,
  buildBriefingUserPrompt,
} from "../../lib/claude";
import { sendBriefingEmail } from "../../lib/resend";

export const generateBriefing = action({
  args: {},
  handler: async (ctx) => {
    // 1. Get current metrics
    const metrics = await ctx.runQuery(api.queries.dashboard.getMetrics);

    // 2. Generate briefing with Claude
    let content: string;
    try {
      const userPrompt = buildBriefingUserPrompt(metrics);
      content = await callClaude(BRIEFING_SYSTEM_PROMPT, userPrompt);
    } catch (err) {
      console.error("Claude API failed, using fallback:", err);
      // Fallback: raw metrics
      content = `## Morning Briefing (Automated Fallback)\n\n- Active Clients: ${metrics.activeClients}\n- Today's Appointments: ${metrics.todayAppointments}\n- Yesterday's No-Shows: ${metrics.noShows}\n- This Week Revenue: $${(metrics.weekRevenue / 100).toFixed(2)}\n- Last Week Revenue: $${(metrics.lastWeekRevenue / 100).toFixed(2)}\n- Aging Claims: ${metrics.agingClaimsCount} totaling $${(metrics.agingClaimsAmount / 100).toFixed(2)}\n\n*Note: AI-generated analysis unavailable. Raw metrics shown.*`;
    }

    // 3. Send email
    const emailTo = process.env.BRIEFING_EMAIL_TO ?? "demo@example.com";
    const today = new Date().toLocaleDateString("en-US", {
      weekday: "long",
      month: "long",
      day: "numeric",
    });

    const htmlContent = `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background: linear-gradient(135deg, #1e3a5f 0%, #2d5a87 100%); padding: 24px; border-radius: 12px 12px 0 0;">
          <h1 style="color: white; margin: 0; font-size: 20px;">Meridian Behavioral Health</h1>
          <p style="color: #93c5fd; margin: 4px 0 0;">Daily Intelligence Briefing — ${today}</p>
        </div>
        <div style="background: #f8fafc; padding: 24px; border: 1px solid #e2e8f0; border-top: none; border-radius: 0 0 12px 12px;">
          <div style="white-space: pre-wrap; line-height: 1.6; color: #334155;">
${content.replace(/##\s/g, "<h2 style='color: #1e3a5f; font-size: 16px; margin-top: 20px;'>").replace(/\n### /g, "\n<h3 style='color: #475569; font-size: 14px; margin-top: 16px;'>").replace(/⚠️/g, "⚠️")}
          </div>
        </div>
        <p style="color: #94a3b8; font-size: 12px; text-align: center; margin-top: 16px;">
          Generated by Meridian BH Automation Suite
        </p>
      </div>
    `;

    let emailSent = false;
    let emailId: string | undefined;

    try {
      const result = await sendBriefingEmail(
        emailTo,
        `Meridian BH — Morning Briefing: ${today}`,
        htmlContent
      );
      if (result) {
        emailSent = true;
        emailId = result;
      }
    } catch (err) {
      console.error("Email send failed:", err);
    }

    // 4. Store briefing
    await ctx.runMutation(internal.mutations.briefings.store, {
      content,
      metrics: {
        activeClients: metrics.activeClients,
        noShows: metrics.noShows,
        weekRevenue: metrics.weekRevenue,
        lastWeekRevenue: metrics.lastWeekRevenue,
        agingClaimsCount: metrics.agingClaimsCount,
        agingClaimsAmount: metrics.agingClaimsAmount,
      },
      emailSent,
      emailId,
    });

    return { content, emailSent };
  },
});
